# General config options
[config]
enableDataSetMapping = "yes"    # yes/no, try mapping the source data set to target data set

# Filters specifying which asset hierarchies to include in the replication
[denyList]
rootAssetExternalId = []           # leave empty for no deny list
[allowList]
dataSetExternalId = ["*"]           # "*" includes all data sets
rootAssetExternalId = ["*"]        # "*" includes all asset hierarchies